version: '3.5'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_DATABASE: zabbix
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server
    volumes:
      - ./zabbix-init:/docker-entrypoint-initdb.d

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysql-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_DATABASE: zabbix
    ports:
      - "8181:8080"
    depends_on:
      - zabbix-server

  mysql-server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
